# Generated by Django 5.0 on 2023-12-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
